spring:
  datasource:
    url: jdbc:h2:~/google_scrape;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console