#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE


google:
  url: https://www.google.com/search

#    show-sql: true
#    properties:
#      hibernate:
#        format_sql=true: true

locations:
  all: false

categories:
  all: true


request:
  total-records: 500


fixedDelay:
  in:
    milliseconds: 6000


app:
  scheduling:
    enable: false

profilebaba:
  save-vendor:
    host: https://testing.profilebaba.com/api
    endpoint: /save-vendor